gui:
  theme:
    activeBorderColor:
      - "#a6e3a1"
      - bold
    inactiveBorderColor:
      - "#cdd6f4"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitFgColor:
      - "#89b4fa"
    cherryPickedCommitBgColor:
      - "#45475a"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"
  nerdFontsVersion: "3"
  showFileTree: true
  showRandomTip: false
  showCommandLog: false

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

os:
  editPreset: "nvim"

keybinding:
  universal:
    quit: "q"
